services:
  mongodb-primary:
    image: mongo:4.4
    container_name: mongodb-primary
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - '../mongo/mongodb-primary/db:/data/db'
    networks:
      - erotic_site
    command: >
      bash -c "
        mongod --replSet rs0 --bind_ip_all &
        echo 'Esperando Mongo...'
        until mongo --eval 'print(\"ready\")' >/dev/null 2>&1; do
          sleep 2
        done
        echo 'Inicializando replica set...'
        mongo --eval '
          rs.initiate({
            _id: \"rs0\",
            members: [{ _id: 0, host: \"mongodb-primary:27017\" }]
          })
        ' || true
        wait
      "

networks:
  erotic_site:
    name: erotic_site
    driver: bridge