services:
  backend:
    container_name: backend
    restart: always
    build:
      context: ..
      dockerfile: docker/dockerfile
    env_file:
      - ../.env
    volumes:
      - ../uploads:/app/uploads
    ports:
      - '${PORT}:${PORT}'
    networks:
      - erotic_site

networks:
  erotic_site:
    name: erotic_site
    driver: bridge
