export enum Language {
  ENGLISH = 'english',
  SPANISH = 'spanish',
  FRENCH = 'french',
  GERMAN = 'german',
  ITALIAN = 'italian',
  PORTUGUESE = 'portuguese',
  RUSSIAN = 'russian',
  CHINESE = 'chinese',
  JAPANESE = 'japanese',
  KOREAN = 'korean',
  ARABIC = 'arabic',
  HINDI = 'hindi',
  BENGALI = 'bengali',
  PUNJABI = 'punjabi',
  VIETNAMESE = 'vietnamese',
  TURKISH = 'turkish',
  POLISH = 'polish',
  DUTCH = 'dutch',
  GREEK = 'greek',
  HEBREW = 'hebrew',
  THAI = 'thai',
  INDONESIAN = 'indonesian',
}
