export enum ModelCategory {
  MILF = 'milf',
  TATTOOED = 'tattooed',
  BIG_BOOTY = 'big_booty',
  PETITE = 'petite',
  BLONDE = 'blonde',
  BRUNETTE = 'brunette',
  REDHEAD = 'redhead',
  LATINA = 'latina',
  ASIAN = 'asian',
  EUROPEAN = 'european',
  AFRO = 'afro',
  TRANS = 'trans',
  NATURAL = 'natural',
  ENHANCED = 'enhanced',
  FITNESS = 'fitness',
  CURVY = 'curvy',
  TEEN = 'teen',
  MATURE = 'mature',
  EXOTIC = 'exotic',
  ELEGANT = 'elegant',
}
